import { mulberry32 } from "./random.js";

const ADJECTIVES = [
  "Ancient",
  "Ashen",
  "Blighted",
  "Bone",
  "Burning",
  "Crimson",
  "Cursed",
  "Dark",
  "Decayed",
  "Deep",
  "Dire",
  "Dread",
  "Eldritch",
  "Ember",
  "Eternal",
  "Fallen",
  "Fetid",
  "Forgotten",
  "Forsaken",
  "Frozen",
  "Ghastly",
  "Gloomy",
  "Grim",
  "Hallowed",
  "Haunted",
  "Hidden",
  "Hollow",
  "Infernal",
  "Iron",
  "Lost",
  "Molten",
  "Obsidian",
  "Pale",
  "Phantom",
  "Putrid",
  "Rotten",
  "Ruined",
  "Sacred",
  "Shadow",
  "Shattered",
  "Silent",
  "Sinister",
  "Spectral",
  "Stone",
  "Sunken",
  "Thorned",
  "Twisted",
  "Unholy",
  "Veiled",
  "Wicked",
  "Withered",
] as const;

const NOUNS = [
  "Abyss",
  "Barrows",
  "Bastion",
  "Burrow",
  "Catacomb",
  "Cavern",
  "Chamber",
  "Citadel",
  "Cloister",
  "Corridor",
  "Crypt",
  "Delve",
  "Den",
  "Depths",
  "Dungeon",
  "Enclave",
  "Fortress",
  "Gallery",
  "Grotto",
  "Halls",
  "Hollow",
  "Keep",
  "Labyrinth",
  "Lair",
  "Mausoleum",
  "Mine",
  "Necropolis",
  "Oubliette",
  "Passage",
  "Pit",
  "Prison",
  "Reaches",
  "Sanctum",
  "Sepulcher",
  "Sewers",
  "Shrine",
  "Spire",
  "Stronghold",
  "Tomb",
  "Tunnels",
  "Undercroft",
  "Vault",
  "Warren",
  "Wasteland",
] as const;

/** Generate a deterministic dungeon name from a seed. */
export function generateRoomName(seed: number): string {
  const rng = mulberry32(seed ^ 0x524f4f4d); // mix with "ROOM" constant
  const adj = ADJECTIVES[Math.floor(rng() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(rng() * NOUNS.length)];
  return `${adj} ${noun}`;
}
